/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.oxisto.kotlintree

import com.sun.jna.Pointer
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val log = Logger()
        log.log = object : LogCallback {
            override fun log(payload: Pointer?, type: Int, msg: String) {
                println(msg)
            }
        }

        val parser = Parser()
        TreeSitter.INSTANCE.ts_parser_set_logger(parser, log)
        parser.language = TreeSitterCpp.INSTANCE.tree_sitter_cpp()

        var language = parser.language
        println(language)

        val source = "int main(int argc, char** argv) {}"

        val tree = parser.parseString(null, source)
        println(tree)

        val root = tree.rootNode
        println(root)

        println(root.string)
        println(root.type)

        val node = root.namedChild(0)
        println(node)

        println(node.string)
        println(node.type)

        val notExists = root.namedChild(1)
        println(notExists)
        println(notExists.isNull)

        language = tree.language
        println(language)

        val start = TreeSitter.INSTANCE.ts_node_start_byte(node)
        println(start)

        /*var test = language.symbolName(1)
        println(test)*/
    }
}
