/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.github.oxisto.kotlintree

import com.sun.jna.Pointer
import kotlin.test.Test

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {

        CLibrary.INSTANCE.printf("Hello World")

        val log = Logger()
        log.log = object : LogFunc {
            override fun log(payload: Pointer?, type: Int, msg: String) {
                //System.out.println(msg)
            }
        }

        val parser = Parser()
        TreeSitter.INSTANCE.ts_parser_set_logger(parser, log)
        parser.language = TreeSitterCpp.INSTANCE.tree_sitter_cpp()

        var language = parser.language
        println(language)

        var struct = language?.pointer?.let { Language(it) }

        struct?.read()

        val source = "int main(int argc, char** argv) {}"

        val tree = parser.parseString(null, source)
        tree.rootNode
        println(tree)

        language = tree.language
        println(language)

        var node = Node()

        var start = TreeSitter.INSTANCE.ts_node_start_byte(node)
        println(start)

        var test = language.symbolName(1)
        println(test)
    }
}
